### ISSUE TITLE
Master branch readme formatting issue

### ISSUE THREAD

**Issue by edzhuang** [petcsclub/python-projects#1]
Example of issue in the master branch's readme:
> Create a new branch 3. Click the version control menu on the left sidebar (second one down). 4. You will see a text field that says: "branch: master". Beside that field, you will see a plus sign. Click it to create a new branch, and name it depending on what you're creating (e.g., name the branch battleship if you're making the game battleship)

Raw:
```
3. Create a new branch
	3. Click the version control menu on the left sidebar (second one down).
	4. You will see a text field that says: "branch: master". Beside that field, you will see a plus sign. Click it to create a new branch, and name it depending on what you're creating (e.g., name the branch battleship if you're making the game battleship)
```
Seems like the number ordering for the sub-steps is wrong, so they weren't formatted properly 
Alright epic

**Comment by albertlai431** [comment]
Ah crap that's kinda whack, thanks for letting me know @EdZ543! I'll fix that 😅

**Comment by albertlai431** [comment]
Turns out it was a formatting issue in VS code that wasn't compatible with the way repl.it did it or something... all fixed now!
